//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NJIS.FPZWS.LineControl.Cutting.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CutPartInfoCollector
    {
        public int Id { get; set; }
        public decimal RealWith1 { get; set; }
        public decimal RealLen1 { get; set; }
        public Nullable<decimal> RealWith2 { get; set; }
        public Nullable<decimal> RealLen2 { get; set; }
        public string PartId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> DefectId { get; set; }
        public string WorkshopCode { get; set; }
        public string UserName { get; set; }
        public string FactoryName { get; set; }
        public string ProductionLine { get; set; }
    }
}
