//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NJIS.FPZWS.LineControl.Cutting.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuttingPattern
    {
        public long LineId { get; set; }
        public System.Guid TaskDistributeId { get; set; }
        public string BatchName { get; set; }
        public string ItemName { get; set; }
        public int Cycles { get; set; }
        public int FinishedCycles { get; set; }
        public int CutMaxCount { get; set; }
        public int BookCount { get; set; }
        public int FinishedBookCount { get; set; }
        public int PartCount { get; set; }
        public int FinishedPartCount { get; set; }
        public float FinishedProgress { get; set; }
        public System.DateTime PlanDate { get; set; }
        public short PatternName { get; set; }
        public int CycleTime { get; set; }
        public int TotalTime { get; set; }
        public short NewPatternName { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public System.DateTime UpdatedTime { get; set; }
    }
}
