//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NJIS.FPZWS.LineControl.Cutting.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuttingSawFileRelation
    {
        public int Id { get; set; }
        public System.DateTime PlanDate { get; set; }
        public string BatchName { get; set; }
        public string StackName { get; set; }
        public int StackIndex { get; set; }
        public int BoardCount { get; set; }
        public string SawFileName { get; set; }
        public int SawType { get; set; }
        public string SawFile { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public System.DateTime UpdatedTime { get; set; }
        public Nullable<System.Guid> TaskId { get; set; }
        public Nullable<System.Guid> TaskDistributeId { get; set; }
    }
}
