//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NJIS.FPZWS.LineControl.Cutting.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuttingStackList
    {
        public long LineID { get; set; }
        public string WorkshopCode { get; set; }
        public string StackName { get; set; }
        public int StackIndex { get; set; }
        public string BatchName { get; set; }
        public string RawMaterialID { get; set; }
        public string RawMaterialName { get; set; }
        public string SupplierInfo { get; set; }
        public double RawLength { get; set; }
        public double RawWidth { get; set; }
        public double RawThickness { get; set; }
        public string RawColor { get; set; }
        public Nullable<int> RawOrientation { get; set; }
        public string Information { get; set; }
        public string PatternName { get; set; }
        public string OptimizationRun { get; set; }
        public int StackType { get; set; }
        public Nullable<int> ImportToMesStatus { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
        public System.Guid TaskId { get; set; }
        public string BatchId { get; set; }
        public System.Guid TaskDistributeId { get; set; }
        public string ProductionLine { get; set; }
        public int WMSStatus { get; set; }
        public System.DateTime PlanDate { get; set; }
        public string ItemName { get; set; }
        public string DeviceGroup { get; set; }
        public Nullable<double> BatchProductIndex { get; set; }
        public Nullable<double> StackProductIndex { get; set; }
        public string BatchType { get; set; }
        public string OptimizationBatchName { get; set; }
        public string NcFilePath { get; set; }
        public string LabelFilePath { get; set; }
        public Nullable<int> PanelQty { get; set; }
    }
}
