//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NJIS.FPZWS.LineControl.Cutting.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuttingRawBoardFeedback
    {
        public long LineID { get; set; }
        public string UBID { get; set; }
        public string WorkshopCode { get; set; }
        public string StackName { get; set; }
        public Nullable<int> StackIndex { get; set; }
        public string BatchName { get; set; }
        public string RawMaterialID { get; set; }
        public string RawMaterialName { get; set; }
        public string SupplierInfo { get; set; }
        public string CuttingMachine { get; set; }
        public Nullable<int> SawNumber { get; set; }
        public Nullable<int> RawBoardStatus { get; set; }
        public Nullable<System.DateTime> InsertedInSaw { get; set; }
        public Nullable<System.DateTime> TimeLastPartLeavesSaw { get; set; }
        public Nullable<int> ImportToMesStatus { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
        public string ProductionLine { get; set; }
    }
}
