//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NJIS.FPZWS.LineControl.Cutting.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuttingStackShift
    {
        public long LineId { get; set; }
        public string StackName { get; set; }
        public string StartPlaceNo { get; set; }
        public string EndPlaceNo { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string BatchName { get; set; }
        public System.DateTime PlanDate { get; set; }
    }
}
