//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NJIS.FPZWS.LineControl.Cutting.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuttingPartBackToLine
    {
        public long LineID { get; set; }
        public string barcode { get; set; }
        public Nullable<System.DateTime> received { get; set; }
        public Nullable<int> status { get; set; }
        public string ProductionLine { get; set; }
    }
}
