//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NJIS.FPZWS.LineControl.Cutting.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuttingStackProductionList
    {
        public long LineId { get; set; }
        public string StackName { get; set; }
        public Nullable<int> Status { get; set; }
        public string PlaceNo { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
        public string ProductionLine { get; set; }
        public Nullable<int> PilerNo { get; set; }
    }
}
