//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NJIS.FPZWS.LineControl.Cutting.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuttingSawFile
    {
        public long LineID { get; set; }
        public string WorkshopCode { get; set; }
        public string BatchName { get; set; }
        public string OptimizationRun { get; set; }
        public string SawFile { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Status2 { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
        public Nullable<System.Guid> TaskId { get; set; }
        public int ImportToMesStatus { get; set; }
        public string BatchId { get; set; }
        public Nullable<System.Guid> TaskDistributeId { get; set; }
        public string ProductionLine { get; set; }
    }
}
