//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NJIS.FPZWS.LineControl.Cutting.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuttingMachineFeedback
    {
        public long LineID { get; set; }
        public string ProductionLine { get; set; }
        public string MachineName { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string BaseMachineStateExternalKeyName { get; set; }
        public string DetailMachineStateExternalKeyName { get; set; }
        public string StateDescription { get; set; }
        public Nullable<long> MachineStateId { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
    }
}
