//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NJIS.FPZWS.LineControl.Cutting.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuttingNgPart
    {
        public long LineId { get; set; }
        public string BatchName { get; set; }
        public string OrderNumber { get; set; }
        public string PartId { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.DateTime> UpdatedTime { get; set; }
        public Nullable<float> FinishLength { get; set; }
        public Nullable<float> FinishWidth { get; set; }
        public Nullable<float> FinishThickness { get; set; }
        public Nullable<System.Guid> TaskDistributeId { get; set; }
        public Nullable<System.Guid> TaskId { get; set; }
    }
}
