//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NJIS.FPZWS.LineControl.Cutting.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuttingPartFeedBack
    {
        public long LineID { get; set; }
        public string UPID { get; set; }
        public string PartID { get; set; }
        public string Code { get; set; }
        public string WorkshopCode { get; set; }
        public string ProductionLine { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
        public string CuttingMachine { get; set; }
        public Nullable<int> SawNumber { get; set; }
        public string StackName { get; set; }
        public Nullable<int> StackIndex { get; set; }
        public string BatchName { get; set; }
        public string RawMaterialID { get; set; }
        public string RawMaterialName { get; set; }
        public string SupplierInfo { get; set; }
        public string PatternName { get; set; }
        public string OptimizationRun { get; set; }
        public Nullable<int> LabelStatus { get; set; }
        public Nullable<int> CuttingStatus { get; set; }
        public string StatusInformation { get; set; }
        public Nullable<int> FeedbackStatus { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
