//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NJIS.FPZWS.LineControl.Cutting.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mdb_Parts_Udi
    {
        public long LineId { get; set; }
        public Nullable<short> JOB_INDEX { get; set; }
        public Nullable<short> PART_INDEX { get; set; }
        public string INFO1 { get; set; }
        public string INFO2 { get; set; }
        public string INFO3 { get; set; }
        public string INFO4 { get; set; }
        public string INFO5 { get; set; }
        public string INFO6 { get; set; }
        public string INFO7 { get; set; }
        public string INFO8 { get; set; }
        public string INFO9 { get; set; }
        public string INFO10 { get; set; }
        public string INFO11 { get; set; }
        public string INFO12 { get; set; }
        public string INFO13 { get; set; }
        public string INFO14 { get; set; }
        public string INFO15 { get; set; }
        public string INFO16 { get; set; }
        public string INFO17 { get; set; }
        public string INFO18 { get; set; }
        public string INFO19 { get; set; }
        public string INFO20 { get; set; }
        public string INFO21 { get; set; }
        public string INFO22 { get; set; }
        public string INFO23 { get; set; }
        public string INFO24 { get; set; }
        public string INFO25 { get; set; }
        public string INFO26 { get; set; }
        public string INFO27 { get; set; }
        public string INFO28 { get; set; }
        public string INFO29 { get; set; }
        public string INFO30 { get; set; }
        public string INFO31 { get; set; }
        public string INFO32 { get; set; }
        public string INFO33 { get; set; }
        public string INFO34 { get; set; }
        public string INFO35 { get; set; }
        public string INFO36 { get; set; }
        public string INFO37 { get; set; }
        public string INFO38 { get; set; }
        public string INFO39 { get; set; }
        public string INFO40 { get; set; }
        public string INFO41 { get; set; }
        public string INFO42 { get; set; }
        public string INFO43 { get; set; }
        public string INFO44 { get; set; }
        public string INFO45 { get; set; }
        public string INFO46 { get; set; }
        public string INFO47 { get; set; }
        public string INFO48 { get; set; }
        public string INFO49 { get; set; }
        public string INFO50 { get; set; }
        public string INFO51 { get; set; }
        public string INFO52 { get; set; }
        public string INFO53 { get; set; }
        public string INFO54 { get; set; }
        public string INFO55 { get; set; }
        public string INFO56 { get; set; }
        public string INFO57 { get; set; }
        public string INFO58 { get; set; }
        public string INFO59 { get; set; }
        public string INFO60 { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<System.DateTime> UpdatedTime { get; set; }
        public string CreatedUser { get; set; }
        public string UpdatedUser { get; set; }
        public string BatchId { get; set; }
        public Nullable<System.Guid> TaskId { get; set; }
        public Nullable<long> DepartmentId { get; set; }
        public int ImportToMesStatus { get; set; }
        public Nullable<System.Guid> TaskDistributeId { get; set; }
        public string ProductionLine { get; set; }
        public Nullable<int> Id { get; set; }
    }
}
