//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NJIS.FPZWS.LineControl.Cutting.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartInfo
    {
        public long Id { get; set; }
        public string PartId { get; set; }
        public System.Guid TaskId { get; set; }
        public string Upi { get; set; }
        public string PanelCode { get; set; }
        public string PanelName { get; set; }
        public string TeamCode { get; set; }
        public string BatchCode { get; set; }
        public string ColorCode { get; set; }
        public float Length { get; set; }
        public float Width { get; set; }
        public float Thickness { get; set; }
        public float Weight { get; set; }
        public string UnitName { get; set; }
        public System.DateTime ProductionDate { get; set; }
        public Nullable<int> PanelType { get; set; }
        public string EdgebandColorCode { get; set; }
        public string EdgebandType { get; set; }
        public string EdgebandComments { get; set; }
        public Nullable<long> OrderHeaderId { get; set; }
        public Nullable<long> OrderLineId { get; set; }
        public string OrderNumber { get; set; }
        public string EdgeInformation1 { get; set; }
        public string EdgeInformation2 { get; set; }
        public string EdgeInformation3 { get; set; }
        public string EdgeInformation4 { get; set; }
        public string Materialflow { get; set; }
        public Nullable<float> RawThickness { get; set; }
        public Nullable<float> SawLength { get; set; }
        public Nullable<float> SawWidth { get; set; }
        public string MaterialInformation { get; set; }
        public string VehicleNum { get; set; }
        public Nullable<System.Guid> TaskDistributeId { get; set; }
        public string ProductionLine { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public Nullable<long> OrganizationId { get; set; }
        public Nullable<long> CreatorUserId { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<long> UpdatorUserId { get; set; }
        public Nullable<System.DateTime> UpdatedTime { get; set; }
    }
}
