//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NJIS.FPZWS.LineControl.Cutting.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpiltMDBResult
    {
        public long LineId { get; set; }
        public System.Guid TaskDistributeId { get; set; }
        public System.Guid TaskId { get; set; }
        public string ItemName { get; set; }
        public System.DateTime PlanDate { get; set; }
        public long StackListId { get; set; }
        public string BatchName { get; set; }
        public string MDBFullName { get; set; }
        public string Msg { get; set; }
        public string DeviceName { get; set; }
        public int FinishedStatus { get; set; }
        public Nullable<System.TimeSpan> EstimatedTime { get; set; }
        public Nullable<System.TimeSpan> ActuallyTime { get; set; }
        public int MdbStatus { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public int BatchIndex { get; set; }
        public int ItemIndex { get; set; }
        public Nullable<System.DateTime> ActualPlanDate { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<System.DateTime> StartLoadingTime { get; set; }
    }
}
