//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NJIS.FPZWS.LineControl.Cutting.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskDistribute
    {
        public System.Guid TaskDistributeId { get; set; }
        public string BatchId { get; set; }
        public string BatchCode { get; set; }
        public long DepartmentId { get; set; }
        public System.Guid TaskId { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.DateTime> UpdatedTime { get; set; }
        public string TaskMessage { get; set; }
        public int Version { get; set; }
        public long Id { get; set; }
    }
}
