//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NJIS.FPZWS.LineControl.Cutting.ModelPlus
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchGroupLog
    {
        public long LineId { get; set; }
        public System.DateTime PlanDate { get; set; }
        public string FrontBatchName { get; set; }
        public string BatchName { get; set; }
        public string NextBatchName { get; set; }
        public bool IsConnect { get; set; }
        public int GroupId { get; set; }
        public int BatchIndex { get; set; }
        public bool IsFinished { get; set; }
        public Nullable<System.DateTime> StartLoadingTime { get; set; }
        public int StackListId { get; set; }
        public int Status { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public System.DateTime UpdatedTime { get; set; }
        public string OperationName { get; set; }
        public System.DateTime LogTime { get; set; }
    }
}
