//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NJIS.FPZWS.LineControl.Cutting.ModelPlus
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchNamePilerNoBind
    {
        public int Id { get; set; }
        public string BatchName { get; set; }
        public string StackName { get; set; }
        public int PilerNo { get; set; }
        public long TaskId { get; set; }
        public int Count { get; set; }
        public string ProductCode { get; set; }
        public bool HasUpProtect { get; set; }
        public System.DateTime CreateTime { get; set; }
        public long ReqId { get; set; }
    }
}
