//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NJIS.FPZWS.LineControl.Cutting.ModelPlus
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchProductionDetails
    {
        public int Id { get; set; }
        public string BatchName { get; set; }
        public string ProductCode { get; set; }
        public int Total { get; set; }
        public int DifferenceNumber { get; set; }
        public int Status { get; set; }
    }
}
