//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NJIS.FPZWS.LineControl.Cutting.ModelPlus
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuttingCheckRule
    {
        public long LineId { get; set; }
        public int CheckObject { get; set; }
        public string CheckOperatorArgs { get; set; }
        public int CheckWay { get; set; }
        public string Args { get; set; }
        public bool IsEnable { get; set; }
        public string Message { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public System.DateTime UpdatedTime { get; set; }
        public System.DateTime StartCheckTime { get; set; }
        public Nullable<System.DateTime> EndCheckTime { get; set; }
        public int CurrentCheckCount { get; set; }
        public int CurrentIntervalCount { get; set; }
    }
}
