//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NJIS.FPZWS.LineControl.Cutting.ModelPlus
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceInfos
    {
        public long LineId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string ProductionLine { get; set; }
        public string DeviceName { get; set; }
        public Nullable<int> State { get; set; }
        public string Msg { get; set; }
        public string Remark { get; set; }
        public string ProcessName { get; set; }
        public string DeviceType { get; set; }
        public string DeviceDescription { get; set; }
        public string PlaceNo { get; set; }
        public float Ratio { get; set; }
    }
}
