//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NJIS.FPZWS.LineControl.Cutting.ModelPlus
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatternFeedBack
    {
        public long LineId { get; set; }
        public string DeviceName { get; set; }
        public string MdbName { get; set; }
        public string PatternName { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> FinishedTime { get; set; }
        public int TotallyTime { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public System.DateTime UpdatedTime { get; set; }
    }
}
