//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NJIS.FPZWS.LineControl.Cutting.ModelPlus
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatternLog
    {
        public long LineId { get; set; }
        public System.DateTime PlanDate { get; set; }
        public string BatchName { get; set; }
        public string MdbName { get; set; }
        public int PatternId { get; set; }
        public string Color { get; set; }
        public int BookCount { get; set; }
        public int TotallyTime { get; set; }
        public int PartCount { get; set; }
        public int OffPartCount { get; set; }
        public bool IsNodePattern { get; set; }
        public int OldPatternId { get; set; }
        public bool IsEnable { get; set; }
        public int Status { get; set; }
        public string DeviceName { get; set; }
        public string FileFullPath { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public System.DateTime UpdatedTime { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> FinishedTime { get; set; }
        public string PlanStackName { get; set; }
        public string ActuallyStackName { get; set; }
        public string PlanDeviceName { get; set; }
        public string ActualDeviceName { get; set; }
        public string OperationName { get; set; }
        public System.DateTime LogTime { get; set; }
    }
}
