//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NJIS.FPZWS.LineControl.Cutting.ModelPlus
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatternDetail
    {
        public long LineId { get; set; }
        public string BatchName { get; set; }
        public int PatternId { get; set; }
        public int OldPatternId { get; set; }
        public string PartId { get; set; }
        public bool IsOffPart { get; set; }
        public double Length { get; set; }
        public double Width { get; set; }
        public double Thickness { get; set; }
        public string Color { get; set; }
        public bool IsFinished { get; set; }
        public int PartCount { get; set; }
        public int FinishedPartCount { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public System.DateTime UpdatedTime { get; set; }
    }
}
