//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NJIS.FPZWS.LineControl.Cutting.ModelPlus
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLCLog
    {
        public int Id { get; set; }
        public string Station { get; set; }
        public string TriggerType { get; set; }
        public string Detail { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string LogType { get; set; }
    }
}
