//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NJIS.FPZWS.LineControl.Cutting.ModelPlus
{
    using System;
    using System.Collections.Generic;
    
    public partial class StackLog
    {
        public long LineId { get; set; }
        public System.DateTime PlanDate { get; set; }
        public string StackName { get; set; }
        public int Status { get; set; }
        public string PlanDeviceName { get; set; }
        public string ActualDeviceName { get; set; }
        public string FirstBatchName { get; set; }
        public string SecondBatchName { get; set; }
        public int BookCount { get; set; }
        public int FirstBatchBookCount { get; set; }
        public int SecondBatchBookCount { get; set; }
        public string MainColor { get; set; }
        public int StackListId { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public System.DateTime UpdatedTime { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> FinishedTime { get; set; }
        public string LastStackName { get; set; }
        public string NextStackName { get; set; }
        public string ConnectColor { get; set; }
        public string OperationName { get; set; }
        public System.DateTime LogTime { get; set; }
    }
}
