//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NJIS.FPZWS.LineControl.Edgebanding.Model
{
    using System;
    using NJIS.Model.Attributes;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Collections.Generic;
    
    
    [Table("Edgebanding")]
    [Serializable]
    public partial class Edgebanding
    {
        [Key, Identity]
    [Required]
    	public long Id { get; set; }
        	[StringLength(80)]
    	public string BatchName { get; set; }
        	[StringLength(80)]
    	public string OrderNumber { get; set; }
        [Required]
    	[StringLength(80)]
    	public string BarCode { get; set; }
        	[StringLength(255)]
    	public string Description { get; set; }
        	public Nullable<decimal> Width { get; set; }
        	public Nullable<decimal> Length { get; set; }
        	public Nullable<decimal> Thickness { get; set; }
        	public Nullable<decimal> L1_OFFCUT { get; set; }
        	[StringLength(80)]
    	public string L1_FORMAT { get; set; }
        	[StringLength(80)]
    	public string L1_EDGE { get; set; }
        	[StringLength(80)]
    	public string L1_CORNER { get; set; }
        	[StringLength(80)]
    	public string L1_GROOVE { get; set; }
        	[StringLength(80)]
    	public string L1_EDGECODE { get; set; }
        	[StringLength(80)]
    	public string L2_FORMAT { get; set; }
        	[StringLength(80)]
    	public string L2_EDGE { get; set; }
        	[StringLength(80)]
    	public string L2_CORNER { get; set; }
        	[StringLength(80)]
    	public string L2_EDGECODE { get; set; }
        	public Nullable<decimal> C1_OFFCUT { get; set; }
        	[StringLength(80)]
    	public string C1_FORMAT { get; set; }
        	[StringLength(80)]
    	public string C1_EDGE { get; set; }
        	[StringLength(80)]
    	public string C1_CORNER { get; set; }
        	[StringLength(80)]
    	public string C1_EDGECODE { get; set; }
        	[StringLength(80)]
    	public string C1_GROOVE { get; set; }
        	[StringLength(80)]
    	public string C2_FORMAT { get; set; }
        	[StringLength(80)]
    	public string C2_EDGE { get; set; }
        	[StringLength(80)]
    	public string C2_CORNER { get; set; }
        	[StringLength(80)]
    	public string C2_EDGECODE { get; set; }
        	[CreatedAt]
    	[IgnoreUpdate]	public Nullable<System.DateTime> CreatedTime { get; set; }
        	[UpdatedAt]
    	public Nullable<System.DateTime> UpdatedTime { get; set; }
        [Required]
    	public System.Guid TaskId { get; set; }
        	public Nullable<System.Guid> TaskDistributeId { get; set; }
        	public Nullable<int> Status1 { get; set; }
        	public Nullable<int> Status2 { get; set; }
    }
}
