//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcsModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachineHandTaskLog
    {
        public long Id { get; set; }
        public long TaskId { get; set; }
        public int FromStation { get; set; }
        public int ToStation { get; set; }
        public long SortingTaskId { get; set; }
        public string ProductCode { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> FinishedTime { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public System.DateTime UpdatedTime { get; set; }
        public int Status { get; set; }
        public int OperationCount { get; set; }
        public int CurOperationCount { get; set; }
        public string OperationName { get; set; }
    }
}
