//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcsModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SortingTaskStatus
    {
        public int id { get; set; }
        public int StationNo { get; set; }
        public string BatchName { get; set; }
        public long SortingTaskId { get; set; }
        public string ProductCode { get; set; }
        public int ColorIndex { get; set; }
        public int CurBookCount { get; set; }
        public int NeedBookCount { get; set; }
        public bool IsFinished { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public System.DateTime UpdatedTime { get; set; }
        public long GroupId { get; set; }
    }
}
