//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcsModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SortingDetail
    {
        public long TaskId { get; set; }
        public int StartFromBookCount { get; set; }
        public int EndFromBookCount { get; set; }
        public int StartToBookCount { get; set; }
        public int EndToBookCount { get; set; }
        public int FromStation { get; set; }
        public int ToStation { get; set; }
        public int MainPilerNo { get; set; }
        public int ParallelPilerNo { get; set; }
        public bool IsReverseSorting { get; set; }
        public bool MainPilerIsFinished { get; set; }
        public bool ParallelPilerIsFinished { get; set; }
        public string ProductCode { get; set; }
        public int BookCount { get; set; }
        public int CurOperationCount { get; set; }
        public int StartPilerNo { get; set; }
        public long SortingTaskId { get; set; }
        public int OperationCount { get; set; }
        public long ParallelSortingTaskId { get; set; }
        public long GroupId { get; set; }
    }
}
