//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcsModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SortingInStockRequest
    {
        public long Id { get; set; }
        public long SortingTaskId { get; set; }
        public int FromStation { get; set; }
        public bool IsRequest { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public System.DateTime UpdatedTime { get; set; }
        public long ReqId { get; set; }
    }
}
