//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcsModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpSolution
    {
        public long Id { get; set; }
        public long GroupId { get; set; }
        public int SolutionId { get; set; }
        public long SortingTaskId { get; set; }
        public int SortingBookCount { get; set; }
        public int PilerBookCount { get; set; }
        public int PilerNo { get; set; }
        public long TaskId { get; set; }
        public string ProductCode { get; set; }
        public int OperationCount { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public System.DateTime UpdatedTime { get; set; }
        public bool IsReverse { get; set; }
        public bool IsParallel { get; set; }
        public int SortingIndex { get; set; }
        public int ParallelIndex { get; set; }
        public bool IsOffPiler { get; set; }
    }
}
