//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcsModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WCS_DeviceMonitor
    {
        public int SId { get; set; }
        public string DeviceNo { get; set; }
        public Nullable<int> ItemNo { get; set; }
        public Nullable<int> PilerNo { get; set; }
        public Nullable<int> Target { get; set; }
        public Nullable<bool> Staus { get; set; }
    }
}
