//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data;

using System.Data.SqlClient;

using System;

using NJIS.Dapper.Repositories;

using NJIS.Dapper.Repositories.SqlGenerator;


public partial class FileMprInfoRepository : DapperRepository<FileMprInfo>,IRepository
{
		public FileMprInfoRepository() : this(DbConnectSetting.Current.GetConnectString()){} 
public FileMprInfoRepository(string connectString) : base(new SqlConnection(connectString)){} 
public FileMprInfoRepository(IDbConnection connection, ESqlConnector sqlConnector) : base(connection, sqlConnector){} 
public FileMprInfoRepository(IDbConnection connection, ISqlGenerator<FileMprInfo> sqlGenerator) : base(connection, sqlGenerator){} 
public FileMprInfoRepository(IDbConnection connection, SqlGeneratorConfig config) : base(connection, config){}
}

