//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NJIS.FPZWS.LineControl.Edgebanding.Repository
{
    using NJIS.FPZWS.LineControl.Edgebanding.Model;
    using System.Data;
    using System;
    using NJIS.Dapper.Repositories;
    using NJIS.Dapper.Repositories.SqlGenerator;
    using System.Data.SqlClient;
    
    public partial class PcsEdgebandQueueRepository : DapperRepository<PcsEdgebandQueue>
    {
    		public PcsEdgebandQueueRepository(string connectString) : base(new SqlConnection(connectString)){} 
    	public PcsEdgebandQueueRepository(IDbConnection connection, ESqlConnector sqlConnector) : base(connection, sqlConnector){} 
    	public PcsEdgebandQueueRepository(IDbConnection connection, ISqlGenerator<PcsEdgebandQueue> sqlGenerator) : base(connection, sqlGenerator){} 
    	public PcsEdgebandQueueRepository(IDbConnection connection, SqlGeneratorConfig config) : base(connection, config){}
    }
    
}
