//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCS.WebServiceDemo {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WMSInParams", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class WMSInParams : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ReqTypeField;
        
        private long ReqIdField;
        
        private System.Nullable<long> TaskIdField;
        
        private System.Nullable<int> PilerNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductCodeField;
        
        private System.Nullable<int> CountField;
        
        private System.Nullable<int> ToStationField;
        
        private System.Nullable<int> FromStationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ReqType {
            get {
                return this.ReqTypeField;
            }
            set {
                if ((this.ReqTypeField.Equals(value) != true)) {
                    this.ReqTypeField = value;
                    this.RaisePropertyChanged("ReqType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public long ReqId {
            get {
                return this.ReqIdField;
            }
            set {
                if ((this.ReqIdField.Equals(value) != true)) {
                    this.ReqIdField = value;
                    this.RaisePropertyChanged("ReqId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<long> TaskId {
            get {
                return this.TaskIdField;
            }
            set {
                if ((this.TaskIdField.Equals(value) != true)) {
                    this.TaskIdField = value;
                    this.RaisePropertyChanged("TaskId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<int> PilerNo {
            get {
                return this.PilerNoField;
            }
            set {
                if ((this.PilerNoField.Equals(value) != true)) {
                    this.PilerNoField = value;
                    this.RaisePropertyChanged("PilerNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ProductCode {
            get {
                return this.ProductCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductCodeField, value) != true)) {
                    this.ProductCodeField = value;
                    this.RaisePropertyChanged("ProductCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<int> Count {
            get {
                return this.CountField;
            }
            set {
                if ((this.CountField.Equals(value) != true)) {
                    this.CountField = value;
                    this.RaisePropertyChanged("Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<int> ToStation {
            get {
                return this.ToStationField;
            }
            set {
                if ((this.ToStationField.Equals(value) != true)) {
                    this.ToStationField = value;
                    this.RaisePropertyChanged("ToStation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<int> FromStation {
            get {
                return this.FromStationField;
            }
            set {
                if ((this.FromStationField.Equals(value) != true)) {
                    this.FromStationField = value;
                    this.RaisePropertyChanged("FromStation");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultMsg", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ResultMsg : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        private long ReqIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public long ReqId {
            get {
                return this.ReqIdField;
            }
            set {
                if ((this.ReqIdField.Equals(value) != true)) {
                    this.ReqIdField = value;
                    this.RaisePropertyChanged("ReqId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebServiceDemo.WMSServiceSoap")]
    public interface WMSServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 inParams 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ApplyWMSTask", ReplyAction="*")]
        WCS.WebServiceDemo.ApplyWMSTaskResponse ApplyWMSTask(WCS.WebServiceDemo.ApplyWMSTaskRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ApplyWMSTask", ReplyAction="*")]
        System.Threading.Tasks.Task<WCS.WebServiceDemo.ApplyWMSTaskResponse> ApplyWMSTaskAsync(WCS.WebServiceDemo.ApplyWMSTaskRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ApplyWMSTaskRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ApplyWMSTask", Namespace="http://tempuri.org/", Order=0)]
        public WCS.WebServiceDemo.ApplyWMSTaskRequestBody Body;
        
        public ApplyWMSTaskRequest() {
        }
        
        public ApplyWMSTaskRequest(WCS.WebServiceDemo.ApplyWMSTaskRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ApplyWMSTaskRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WCS.WebServiceDemo.WMSInParams inParams;
        
        public ApplyWMSTaskRequestBody() {
        }
        
        public ApplyWMSTaskRequestBody(WCS.WebServiceDemo.WMSInParams inParams) {
            this.inParams = inParams;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ApplyWMSTaskResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ApplyWMSTaskResponse", Namespace="http://tempuri.org/", Order=0)]
        public WCS.WebServiceDemo.ApplyWMSTaskResponseBody Body;
        
        public ApplyWMSTaskResponse() {
        }
        
        public ApplyWMSTaskResponse(WCS.WebServiceDemo.ApplyWMSTaskResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ApplyWMSTaskResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WCS.WebServiceDemo.ResultMsg ApplyWMSTaskResult;
        
        public ApplyWMSTaskResponseBody() {
        }
        
        public ApplyWMSTaskResponseBody(WCS.WebServiceDemo.ResultMsg ApplyWMSTaskResult) {
            this.ApplyWMSTaskResult = ApplyWMSTaskResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WMSServiceSoapChannel : WCS.WebServiceDemo.WMSServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WMSServiceSoapClient : System.ServiceModel.ClientBase<WCS.WebServiceDemo.WMSServiceSoap>, WCS.WebServiceDemo.WMSServiceSoap {
        
        public WMSServiceSoapClient() {
        }
        
        public WMSServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WMSServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WMSServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WMSServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCS.WebServiceDemo.ApplyWMSTaskResponse WCS.WebServiceDemo.WMSServiceSoap.ApplyWMSTask(WCS.WebServiceDemo.ApplyWMSTaskRequest request) {
            return base.Channel.ApplyWMSTask(request);
        }
        
        public WCS.WebServiceDemo.ResultMsg ApplyWMSTask(WCS.WebServiceDemo.WMSInParams inParams) {
            WCS.WebServiceDemo.ApplyWMSTaskRequest inValue = new WCS.WebServiceDemo.ApplyWMSTaskRequest();
            inValue.Body = new WCS.WebServiceDemo.ApplyWMSTaskRequestBody();
            inValue.Body.inParams = inParams;
            WCS.WebServiceDemo.ApplyWMSTaskResponse retVal = ((WCS.WebServiceDemo.WMSServiceSoap)(this)).ApplyWMSTask(inValue);
            return retVal.Body.ApplyWMSTaskResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WCS.WebServiceDemo.ApplyWMSTaskResponse> WCS.WebServiceDemo.WMSServiceSoap.ApplyWMSTaskAsync(WCS.WebServiceDemo.ApplyWMSTaskRequest request) {
            return base.Channel.ApplyWMSTaskAsync(request);
        }
        
        public System.Threading.Tasks.Task<WCS.WebServiceDemo.ApplyWMSTaskResponse> ApplyWMSTaskAsync(WCS.WebServiceDemo.WMSInParams inParams) {
            WCS.WebServiceDemo.ApplyWMSTaskRequest inValue = new WCS.WebServiceDemo.ApplyWMSTaskRequest();
            inValue.Body = new WCS.WebServiceDemo.ApplyWMSTaskRequestBody();
            inValue.Body.inParams = inParams;
            return ((WCS.WebServiceDemo.WMSServiceSoap)(this)).ApplyWMSTaskAsync(inValue);
        }
    }
}
