//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NJIS.FPZWS.LineControl.Drilling.Model
{
    using System;
    using NJIS.Model.Attributes;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Collections.Generic;
    
    
    [Table("Drilling")]
    [Serializable]
    public partial class Drilling
    {
        [Key, Identity]
    [Required]
    	public long LineID { get; set; }
        	[StringLength(80)]
    	public string PartID { get; set; }
        	[StringLength(160)]
    	public string BatchName { get; set; }
        	[StringLength(80)]
    	public string OrderNumber { get; set; }
        	public Nullable<float> FinishLength { get; set; }
        	public Nullable<float> FinishWidth { get; set; }
        	public Nullable<float> FinishThickness { get; set; }
        	public string DrillingProgram { get; set; }
        	[StringLength(50)]
    	public string DrillingProgramMD5 { get; set; }
        	public Nullable<int> DrillingProgramFileEncoding { get; set; }
        	public Nullable<int> DrillingRotation { get; set; }
        	[StringLength(100)]
    	public string DrillingType { get; set; }
        	[StringLength(50)]
    	public string DrillingRouting { get; set; }
        	public Nullable<int> ImportToMesStatus { get; set; }
        	[CreatedAt]
    	[IgnoreUpdate]	public Nullable<System.DateTime> CreatedTime { get; set; }
        	[UpdatedAt]
    	public Nullable<System.DateTime> UpdatedTime { get; set; }
        	[StringLength(60)]
    	public string WorkshopCode { get; set; }
        	public Nullable<System.DateTime> ProductionDate { get; set; }
        	public Nullable<System.Guid> TaskId { get; set; }
        	public Nullable<System.Guid> TaskDistributeId { get; set; }
        	[StringLength(60)]
    	public string ProductionLine { get; set; }
        	public string DrillingProgram1 { get; set; }
        	[StringLength(80)]
    	public string FactoryCode { get; set; }
        	[StringLength(80)]
    	public string MaterialInformation { get; set; }
        	[StringLength(80)]
    	public string Materialflow { get; set; }
        	[StringLength(80)]
    	public string OrderHeaderId { get; set; }
    }
}
