//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NJIS.FPZWS.LineControl.Drilling.Model
{
    using System;
    using NJIS.Model.Attributes;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Collections.Generic;
    
    
    [Table("PcsMachine")]
    [Serializable]
    public partial class PcsMachine
    {
        [Key, Identity]
    [Required]
    	public long LineId { get; set; }
        	[StringLength(80)]
    	public string SN { get; set; }
        	[StringLength(80)]
    	public string Code { get; set; }
        	[StringLength(80)]
    	public string Name { get; set; }
        	public Nullable<int> Status { get; set; }
        [Required]
    	public int IsProcessSingle { get; set; }
        [Required]
    	public int IsProcessDouble { get; set; }
    }
}
