//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NJIS.FPZWS.LineControl.Drilling.Model
{
    using System;
    using NJIS.Model.Attributes;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Collections.Generic;
    
    
    [Table("PcsNg")]
    [Serializable]
    public partial class PcsNg
    {
        [Key, Identity]
    [Required]
    	public long LineId { get; set; }
        	[StringLength(80)]
    	public string PartId { get; set; }
        	[StringLength(200)]
    	public string Msg { get; set; }
        	public Nullable<int> Status { get; set; }
        [Required]
    	[CreatedAt]
    	[IgnoreUpdate]	public System.DateTime CreatedTime { get; set; }
        [Required]
    	[UpdatedAt]
    	public System.DateTime UpdatedTime { get; set; }
    }
}
