//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NJIS.FPZWS.LineControl.Drilling.Model
{
    using System;
    using NJIS.Model.Attributes;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Collections.Generic;
    
    
    [Table("PcsPartInfoQueue")]
    [Serializable]
    public partial class PcsPartInfoQueue
    {
        [Key, Identity]
    [Required]
    	public long LineId { get; set; }
        [Required]
    	[StringLength(80)]
    	public string PartId { get; set; }
        [Required]
    	[StringLength(160)]
    	public string BatchName { get; set; }
        [Required]
    	[StringLength(80)]
    	public string OrderNumber { get; set; }
        	[StringLength(80)]
    	public string Place { get; set; }
        	[StringLength(80)]
    	public string NextPlace { get; set; }
        [Required]
    	[StringLength(50)]
    	public string DrillingRouting { get; set; }
        [Required]
    	public float FinishLength { get; set; }
        [Required]
    	public float FinishWidth { get; set; }
        [Required]
    	public float FinishThickness { get; set; }
        	[StringLength(256)]
    	public string PcsMessage { get; set; }
        [Required]
    	[CreatedAt]
    	[IgnoreUpdate]	public System.DateTime CreatedTime { get; set; }
        [Required]
    	[UpdatedAt]
    	public System.DateTime UpdatedTime { get; set; }
        [Required]
    	public int Status { get; set; }
        	public Nullable<bool> IsNg { get; set; }
    }
}
