//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCS.WebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.primeton.com/interface2wcsService", ConfigurationName="WebService.interface2wcsService")]
    public interface interface2wcsService {
        
        // CODEGEN: 操作 appleReworkLocator 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WCS.WebService.appleReworkLocatorResponse1 appleReworkLocator(WCS.WebService.appleReworkLocator1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WCS.WebService.appleReworkLocatorResponse1> appleReworkLocatorAsync(WCS.WebService.appleReworkLocator1 request);
        
        // CODEGEN: 操作 applyTask 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WCS.WebService.applyTaskResponse1 applyTask(WCS.WebService.applyTask1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WCS.WebService.applyTaskResponse1> applyTaskAsync(WCS.WebService.applyTask1 request);
        
        // CODEGEN: 操作 createTask 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WCS.WebService.createTaskResponse1 createTask(WCS.WebService.createTask1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WCS.WebService.createTaskResponse1> createTaskAsync(WCS.WebService.createTask1 request);
        
        // CODEGEN: 操作 updateScStatus 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WCS.WebService.updateScStatusResponse1 updateScStatus(WCS.WebService.updateScStatus1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WCS.WebService.updateScStatusResponse1> updateScStatusAsync(WCS.WebService.updateScStatus1 request);
        
        // CODEGEN: 操作 updateStationStatus 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WCS.WebService.updateStationStatusResponse1 updateStationStatus(WCS.WebService.updateStationStatus1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WCS.WebService.updateStationStatusResponse1> updateStationStatusAsync(WCS.WebService.updateStationStatus1 request);
        
        // CODEGEN: 操作 updateTaskStatus 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WCS.WebService.updateTaskStatusResponse1 updateTaskStatus(WCS.WebService.updateTaskStatus1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WCS.WebService.updateTaskStatusResponse1> updateTaskStatusAsync(WCS.WebService.updateTaskStatus1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.primeton.com/interface2wcsService")]
    public partial class appleReworkLocator : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sEQIDField;
        
        private int nORDIDField;
        
        private bool nORDIDFieldSpecified;
        
        private string cSYSTYPEField;
        
        private string nPALLETIDField;
        
        private string nOPTTYPEField;
        
        private string nOPTSTATIONField;
        
        private string cWHIDField;
        
        private string qUANTITYField;
        
        private string hEIGHTField;
        
        private string dOPTDATEField;
        
        private string cAPPREASONField;
        
        private string nREASONCODEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string SEQID {
            get {
                return this.sEQIDField;
            }
            set {
                this.sEQIDField = value;
                this.RaisePropertyChanged("SEQID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int NORDID {
            get {
                return this.nORDIDField;
            }
            set {
                this.nORDIDField = value;
                this.RaisePropertyChanged("NORDID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NORDIDSpecified {
            get {
                return this.nORDIDFieldSpecified;
            }
            set {
                this.nORDIDFieldSpecified = value;
                this.RaisePropertyChanged("NORDIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string CSYSTYPE {
            get {
                return this.cSYSTYPEField;
            }
            set {
                this.cSYSTYPEField = value;
                this.RaisePropertyChanged("CSYSTYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string NPALLETID {
            get {
                return this.nPALLETIDField;
            }
            set {
                this.nPALLETIDField = value;
                this.RaisePropertyChanged("NPALLETID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string NOPTTYPE {
            get {
                return this.nOPTTYPEField;
            }
            set {
                this.nOPTTYPEField = value;
                this.RaisePropertyChanged("NOPTTYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string NOPTSTATION {
            get {
                return this.nOPTSTATIONField;
            }
            set {
                this.nOPTSTATIONField = value;
                this.RaisePropertyChanged("NOPTSTATION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string CWHID {
            get {
                return this.cWHIDField;
            }
            set {
                this.cWHIDField = value;
                this.RaisePropertyChanged("CWHID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string QUANTITY {
            get {
                return this.qUANTITYField;
            }
            set {
                this.qUANTITYField = value;
                this.RaisePropertyChanged("QUANTITY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string HEIGHT {
            get {
                return this.hEIGHTField;
            }
            set {
                this.hEIGHTField = value;
                this.RaisePropertyChanged("HEIGHT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string DOPTDATE {
            get {
                return this.dOPTDATEField;
            }
            set {
                this.dOPTDATEField = value;
                this.RaisePropertyChanged("DOPTDATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string CAPPREASON {
            get {
                return this.cAPPREASONField;
            }
            set {
                this.cAPPREASONField = value;
                this.RaisePropertyChanged("CAPPREASON");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string NREASONCODE {
            get {
                return this.nREASONCODEField;
            }
            set {
                this.nREASONCODEField = value;
                this.RaisePropertyChanged("NREASONCODE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="com.sfy.wms.autowarehouse.interface2wcs.wcsInterfaceParam")]
    public partial class TaskInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sEQIDField;
        
        private System.Nullable<int> nWORKIDField;
        
        private bool nWORKIDFieldSpecified;
        
        private System.Nullable<int> nORDIDField;
        
        private bool nORDIDFieldSpecified;
        
        private System.Nullable<int> sOURCETYPEField;
        
        private bool sOURCETYPEFieldSpecified;
        
        private string cSYSTYPEField;
        
        private string nPALLETIDField;
        
        private string nOPTTYPEField;
        
        private System.Nullable<int> nOPTSTATIONField;
        
        private bool nOPTSTATIONFieldSpecified;
        
        private System.Nullable<int> oRGANIZATION_IDField;
        
        private bool oRGANIZATION_IDFieldSpecified;
        
        private string fROM_SUBINVENTORY_CODEField;
        
        private string tO_SUBINVENTORY_CODEField;
        
        private string fROM_LOCATOR_CODEField;
        
        private string tO_LOCATOR_CODEField;
        
        private System.Nullable<int> fROM_LOCATOR_IDField;
        
        private bool fROM_LOCATOR_IDFieldSpecified;
        
        private System.Nullable<int> tO_LOCATOR_IDField;
        
        private bool tO_LOCATOR_IDFieldSpecified;
        
        private string fROM_LOCATOR_RACKField;
        
        private string fROM_LOCATOR_COLUMNField;
        
        private string fROM_LOCATOR_LAYERField;
        
        private string tO_LOCATOR_RACKField;
        
        private string tO_LOCATOR_COLUMNField;
        
        private string tO_LOCATOR_LAYERField;
        
        private string cUSERIDField;
        
        private System.Nullable<int> nWKSTATUSField;
        
        private bool nWKSTATUSFieldSpecified;
        
        private System.Nullable<int> nLOTIDField;
        
        private bool nLOTIDFieldSpecified;
        
        private System.Nullable<int> nPRIField;
        
        private bool nPRIFieldSpecified;
        
        private System.Nullable<System.DateTime> dOPTDATEField;
        
        private bool dOPTDATEFieldSpecified;
        
        private System.Nullable<System.DateTime> cOMP_DATEField;
        
        private bool cOMP_DATEFieldSpecified;
        
        private System.Nullable<System.DateTime> cREATION_DATEField;
        
        private bool cREATION_DATEFieldSpecified;
        
        private string eRROR_CODEField;
        
        private string eRROR_MSGField;
        
        private System.Nullable<int> dELIVERY_HEADER_IDField;
        
        private bool dELIVERY_HEADER_IDFieldSpecified;
        
        private string cUSTOMER_NUMBERField;
        
        private string cUSTOMER_NAMEField;
        
        private string cPACKTYPEField;
        
        private System.Nullable<int> nPACKORDERField;
        
        private bool nPACKORDERFieldSpecified;
        
        private string cFINISHMODEField;
        
        private System.Nullable<int> bISALLOWRETURNBACKField;
        
        private bool bISALLOWRETURNBACKFieldSpecified;
        
        private System.Nullable<int> qUANTITYField;
        
        private bool qUANTITYFieldSpecified;
        
        private string lEDMSGField;
        
        private string rESERVE1Field;
        
        private string rESERVE2Field;
        
        private string rESERVE3Field;
        
        private string rESERVE4Field;
        
        private string rESERVE5Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string SEQID {
            get {
                return this.sEQIDField;
            }
            set {
                this.sEQIDField = value;
                this.RaisePropertyChanged("SEQID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public System.Nullable<int> NWORKID {
            get {
                return this.nWORKIDField;
            }
            set {
                this.nWORKIDField = value;
                this.RaisePropertyChanged("NWORKID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NWORKIDSpecified {
            get {
                return this.nWORKIDFieldSpecified;
            }
            set {
                this.nWORKIDFieldSpecified = value;
                this.RaisePropertyChanged("NWORKIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public System.Nullable<int> NORDID {
            get {
                return this.nORDIDField;
            }
            set {
                this.nORDIDField = value;
                this.RaisePropertyChanged("NORDID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NORDIDSpecified {
            get {
                return this.nORDIDFieldSpecified;
            }
            set {
                this.nORDIDFieldSpecified = value;
                this.RaisePropertyChanged("NORDIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public System.Nullable<int> SOURCETYPE {
            get {
                return this.sOURCETYPEField;
            }
            set {
                this.sOURCETYPEField = value;
                this.RaisePropertyChanged("SOURCETYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SOURCETYPESpecified {
            get {
                return this.sOURCETYPEFieldSpecified;
            }
            set {
                this.sOURCETYPEFieldSpecified = value;
                this.RaisePropertyChanged("SOURCETYPESpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string CSYSTYPE {
            get {
                return this.cSYSTYPEField;
            }
            set {
                this.cSYSTYPEField = value;
                this.RaisePropertyChanged("CSYSTYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string NPALLETID {
            get {
                return this.nPALLETIDField;
            }
            set {
                this.nPALLETIDField = value;
                this.RaisePropertyChanged("NPALLETID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string NOPTTYPE {
            get {
                return this.nOPTTYPEField;
            }
            set {
                this.nOPTTYPEField = value;
                this.RaisePropertyChanged("NOPTTYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public System.Nullable<int> NOPTSTATION {
            get {
                return this.nOPTSTATIONField;
            }
            set {
                this.nOPTSTATIONField = value;
                this.RaisePropertyChanged("NOPTSTATION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NOPTSTATIONSpecified {
            get {
                return this.nOPTSTATIONFieldSpecified;
            }
            set {
                this.nOPTSTATIONFieldSpecified = value;
                this.RaisePropertyChanged("NOPTSTATIONSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public System.Nullable<int> ORGANIZATION_ID {
            get {
                return this.oRGANIZATION_IDField;
            }
            set {
                this.oRGANIZATION_IDField = value;
                this.RaisePropertyChanged("ORGANIZATION_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ORGANIZATION_IDSpecified {
            get {
                return this.oRGANIZATION_IDFieldSpecified;
            }
            set {
                this.oRGANIZATION_IDFieldSpecified = value;
                this.RaisePropertyChanged("ORGANIZATION_IDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public string FROM_SUBINVENTORY_CODE {
            get {
                return this.fROM_SUBINVENTORY_CODEField;
            }
            set {
                this.fROM_SUBINVENTORY_CODEField = value;
                this.RaisePropertyChanged("FROM_SUBINVENTORY_CODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=10)]
        public string TO_SUBINVENTORY_CODE {
            get {
                return this.tO_SUBINVENTORY_CODEField;
            }
            set {
                this.tO_SUBINVENTORY_CODEField = value;
                this.RaisePropertyChanged("TO_SUBINVENTORY_CODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=11)]
        public string FROM_LOCATOR_CODE {
            get {
                return this.fROM_LOCATOR_CODEField;
            }
            set {
                this.fROM_LOCATOR_CODEField = value;
                this.RaisePropertyChanged("FROM_LOCATOR_CODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=12)]
        public string TO_LOCATOR_CODE {
            get {
                return this.tO_LOCATOR_CODEField;
            }
            set {
                this.tO_LOCATOR_CODEField = value;
                this.RaisePropertyChanged("TO_LOCATOR_CODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=13)]
        public System.Nullable<int> FROM_LOCATOR_ID {
            get {
                return this.fROM_LOCATOR_IDField;
            }
            set {
                this.fROM_LOCATOR_IDField = value;
                this.RaisePropertyChanged("FROM_LOCATOR_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FROM_LOCATOR_IDSpecified {
            get {
                return this.fROM_LOCATOR_IDFieldSpecified;
            }
            set {
                this.fROM_LOCATOR_IDFieldSpecified = value;
                this.RaisePropertyChanged("FROM_LOCATOR_IDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=14)]
        public System.Nullable<int> TO_LOCATOR_ID {
            get {
                return this.tO_LOCATOR_IDField;
            }
            set {
                this.tO_LOCATOR_IDField = value;
                this.RaisePropertyChanged("TO_LOCATOR_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TO_LOCATOR_IDSpecified {
            get {
                return this.tO_LOCATOR_IDFieldSpecified;
            }
            set {
                this.tO_LOCATOR_IDFieldSpecified = value;
                this.RaisePropertyChanged("TO_LOCATOR_IDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=15)]
        public string FROM_LOCATOR_RACK {
            get {
                return this.fROM_LOCATOR_RACKField;
            }
            set {
                this.fROM_LOCATOR_RACKField = value;
                this.RaisePropertyChanged("FROM_LOCATOR_RACK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=16)]
        public string FROM_LOCATOR_COLUMN {
            get {
                return this.fROM_LOCATOR_COLUMNField;
            }
            set {
                this.fROM_LOCATOR_COLUMNField = value;
                this.RaisePropertyChanged("FROM_LOCATOR_COLUMN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=17)]
        public string FROM_LOCATOR_LAYER {
            get {
                return this.fROM_LOCATOR_LAYERField;
            }
            set {
                this.fROM_LOCATOR_LAYERField = value;
                this.RaisePropertyChanged("FROM_LOCATOR_LAYER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=18)]
        public string TO_LOCATOR_RACK {
            get {
                return this.tO_LOCATOR_RACKField;
            }
            set {
                this.tO_LOCATOR_RACKField = value;
                this.RaisePropertyChanged("TO_LOCATOR_RACK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=19)]
        public string TO_LOCATOR_COLUMN {
            get {
                return this.tO_LOCATOR_COLUMNField;
            }
            set {
                this.tO_LOCATOR_COLUMNField = value;
                this.RaisePropertyChanged("TO_LOCATOR_COLUMN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=20)]
        public string TO_LOCATOR_LAYER {
            get {
                return this.tO_LOCATOR_LAYERField;
            }
            set {
                this.tO_LOCATOR_LAYERField = value;
                this.RaisePropertyChanged("TO_LOCATOR_LAYER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=21)]
        public string CUSERID {
            get {
                return this.cUSERIDField;
            }
            set {
                this.cUSERIDField = value;
                this.RaisePropertyChanged("CUSERID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=22)]
        public System.Nullable<int> NWKSTATUS {
            get {
                return this.nWKSTATUSField;
            }
            set {
                this.nWKSTATUSField = value;
                this.RaisePropertyChanged("NWKSTATUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NWKSTATUSSpecified {
            get {
                return this.nWKSTATUSFieldSpecified;
            }
            set {
                this.nWKSTATUSFieldSpecified = value;
                this.RaisePropertyChanged("NWKSTATUSSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=23)]
        public System.Nullable<int> NLOTID {
            get {
                return this.nLOTIDField;
            }
            set {
                this.nLOTIDField = value;
                this.RaisePropertyChanged("NLOTID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NLOTIDSpecified {
            get {
                return this.nLOTIDFieldSpecified;
            }
            set {
                this.nLOTIDFieldSpecified = value;
                this.RaisePropertyChanged("NLOTIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=24)]
        public System.Nullable<int> NPRI {
            get {
                return this.nPRIField;
            }
            set {
                this.nPRIField = value;
                this.RaisePropertyChanged("NPRI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NPRISpecified {
            get {
                return this.nPRIFieldSpecified;
            }
            set {
                this.nPRIFieldSpecified = value;
                this.RaisePropertyChanged("NPRISpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=25)]
        public System.Nullable<System.DateTime> DOPTDATE {
            get {
                return this.dOPTDATEField;
            }
            set {
                this.dOPTDATEField = value;
                this.RaisePropertyChanged("DOPTDATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DOPTDATESpecified {
            get {
                return this.dOPTDATEFieldSpecified;
            }
            set {
                this.dOPTDATEFieldSpecified = value;
                this.RaisePropertyChanged("DOPTDATESpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=26)]
        public System.Nullable<System.DateTime> COMP_DATE {
            get {
                return this.cOMP_DATEField;
            }
            set {
                this.cOMP_DATEField = value;
                this.RaisePropertyChanged("COMP_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool COMP_DATESpecified {
            get {
                return this.cOMP_DATEFieldSpecified;
            }
            set {
                this.cOMP_DATEFieldSpecified = value;
                this.RaisePropertyChanged("COMP_DATESpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=27)]
        public System.Nullable<System.DateTime> CREATION_DATE {
            get {
                return this.cREATION_DATEField;
            }
            set {
                this.cREATION_DATEField = value;
                this.RaisePropertyChanged("CREATION_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CREATION_DATESpecified {
            get {
                return this.cREATION_DATEFieldSpecified;
            }
            set {
                this.cREATION_DATEFieldSpecified = value;
                this.RaisePropertyChanged("CREATION_DATESpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=28)]
        public string ERROR_CODE {
            get {
                return this.eRROR_CODEField;
            }
            set {
                this.eRROR_CODEField = value;
                this.RaisePropertyChanged("ERROR_CODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=29)]
        public string ERROR_MSG {
            get {
                return this.eRROR_MSGField;
            }
            set {
                this.eRROR_MSGField = value;
                this.RaisePropertyChanged("ERROR_MSG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=30)]
        public System.Nullable<int> DELIVERY_HEADER_ID {
            get {
                return this.dELIVERY_HEADER_IDField;
            }
            set {
                this.dELIVERY_HEADER_IDField = value;
                this.RaisePropertyChanged("DELIVERY_HEADER_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DELIVERY_HEADER_IDSpecified {
            get {
                return this.dELIVERY_HEADER_IDFieldSpecified;
            }
            set {
                this.dELIVERY_HEADER_IDFieldSpecified = value;
                this.RaisePropertyChanged("DELIVERY_HEADER_IDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=31)]
        public string CUSTOMER_NUMBER {
            get {
                return this.cUSTOMER_NUMBERField;
            }
            set {
                this.cUSTOMER_NUMBERField = value;
                this.RaisePropertyChanged("CUSTOMER_NUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=32)]
        public string CUSTOMER_NAME {
            get {
                return this.cUSTOMER_NAMEField;
            }
            set {
                this.cUSTOMER_NAMEField = value;
                this.RaisePropertyChanged("CUSTOMER_NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=33)]
        public string CPACKTYPE {
            get {
                return this.cPACKTYPEField;
            }
            set {
                this.cPACKTYPEField = value;
                this.RaisePropertyChanged("CPACKTYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=34)]
        public System.Nullable<int> NPACKORDER {
            get {
                return this.nPACKORDERField;
            }
            set {
                this.nPACKORDERField = value;
                this.RaisePropertyChanged("NPACKORDER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NPACKORDERSpecified {
            get {
                return this.nPACKORDERFieldSpecified;
            }
            set {
                this.nPACKORDERFieldSpecified = value;
                this.RaisePropertyChanged("NPACKORDERSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=35)]
        public string CFINISHMODE {
            get {
                return this.cFINISHMODEField;
            }
            set {
                this.cFINISHMODEField = value;
                this.RaisePropertyChanged("CFINISHMODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=36)]
        public System.Nullable<int> BISALLOWRETURNBACK {
            get {
                return this.bISALLOWRETURNBACKField;
            }
            set {
                this.bISALLOWRETURNBACKField = value;
                this.RaisePropertyChanged("BISALLOWRETURNBACK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BISALLOWRETURNBACKSpecified {
            get {
                return this.bISALLOWRETURNBACKFieldSpecified;
            }
            set {
                this.bISALLOWRETURNBACKFieldSpecified = value;
                this.RaisePropertyChanged("BISALLOWRETURNBACKSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=37)]
        public System.Nullable<int> QUANTITY {
            get {
                return this.qUANTITYField;
            }
            set {
                this.qUANTITYField = value;
                this.RaisePropertyChanged("QUANTITY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QUANTITYSpecified {
            get {
                return this.qUANTITYFieldSpecified;
            }
            set {
                this.qUANTITYFieldSpecified = value;
                this.RaisePropertyChanged("QUANTITYSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=38)]
        public string LEDMSG {
            get {
                return this.lEDMSGField;
            }
            set {
                this.lEDMSGField = value;
                this.RaisePropertyChanged("LEDMSG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=39)]
        public string RESERVE1 {
            get {
                return this.rESERVE1Field;
            }
            set {
                this.rESERVE1Field = value;
                this.RaisePropertyChanged("RESERVE1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=40)]
        public string RESERVE2 {
            get {
                return this.rESERVE2Field;
            }
            set {
                this.rESERVE2Field = value;
                this.RaisePropertyChanged("RESERVE2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=41)]
        public string RESERVE3 {
            get {
                return this.rESERVE3Field;
            }
            set {
                this.rESERVE3Field = value;
                this.RaisePropertyChanged("RESERVE3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=42)]
        public string RESERVE4 {
            get {
                return this.rESERVE4Field;
            }
            set {
                this.rESERVE4Field = value;
                this.RaisePropertyChanged("RESERVE4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=43)]
        public string RESERVE5 {
            get {
                return this.rESERVE5Field;
            }
            set {
                this.rESERVE5Field = value;
                this.RaisePropertyChanged("RESERVE5");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.primeton.com/interface2wcsService")]
    public partial class appleReworkLocatorResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sTATUSField;
        
        private string mESSAGEField;
        
        private TaskInfo dATAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string STATUS {
            get {
                return this.sTATUSField;
            }
            set {
                this.sTATUSField = value;
                this.RaisePropertyChanged("STATUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
                this.RaisePropertyChanged("MESSAGE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public TaskInfo DATA {
            get {
                return this.dATAField;
            }
            set {
                this.dATAField = value;
                this.RaisePropertyChanged("DATA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class appleReworkLocator1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.primeton.com/interface2wcsService", Order=0)]
        public WCS.WebService.appleReworkLocator appleReworkLocator;
        
        public appleReworkLocator1() {
        }
        
        public appleReworkLocator1(WCS.WebService.appleReworkLocator appleReworkLocator) {
            this.appleReworkLocator = appleReworkLocator;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class appleReworkLocatorResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.primeton.com/interface2wcsService", Order=0)]
        public WCS.WebService.appleReworkLocatorResponse appleReworkLocatorResponse;
        
        public appleReworkLocatorResponse1() {
        }
        
        public appleReworkLocatorResponse1(WCS.WebService.appleReworkLocatorResponse appleReworkLocatorResponse) {
            this.appleReworkLocatorResponse = appleReworkLocatorResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.primeton.com/interface2wcsService")]
    public partial class applyTask : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int nORDIDField;
        
        private bool nORDIDFieldSpecified;
        
        private string cSYSTYPEField;
        
        private string nPALLETIDField;
        
        private string nOPTTYPEField;
        
        private string nOPTSTATIONField;
        
        private string cWHIDField;
        
        private int qUANTITYField;
        
        private bool qUANTITYFieldSpecified;
        
        private int hEIGHTField;
        
        private bool hEIGHTFieldSpecified;
        
        private System.Nullable<System.DateTime> dOPTDATEField;
        
        private bool dOPTDATEFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int NORDID {
            get {
                return this.nORDIDField;
            }
            set {
                this.nORDIDField = value;
                this.RaisePropertyChanged("NORDID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NORDIDSpecified {
            get {
                return this.nORDIDFieldSpecified;
            }
            set {
                this.nORDIDFieldSpecified = value;
                this.RaisePropertyChanged("NORDIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string CSYSTYPE {
            get {
                return this.cSYSTYPEField;
            }
            set {
                this.cSYSTYPEField = value;
                this.RaisePropertyChanged("CSYSTYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string NPALLETID {
            get {
                return this.nPALLETIDField;
            }
            set {
                this.nPALLETIDField = value;
                this.RaisePropertyChanged("NPALLETID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string NOPTTYPE {
            get {
                return this.nOPTTYPEField;
            }
            set {
                this.nOPTTYPEField = value;
                this.RaisePropertyChanged("NOPTTYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string NOPTSTATION {
            get {
                return this.nOPTSTATIONField;
            }
            set {
                this.nOPTSTATIONField = value;
                this.RaisePropertyChanged("NOPTSTATION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string CWHID {
            get {
                return this.cWHIDField;
            }
            set {
                this.cWHIDField = value;
                this.RaisePropertyChanged("CWHID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int QUANTITY {
            get {
                return this.qUANTITYField;
            }
            set {
                this.qUANTITYField = value;
                this.RaisePropertyChanged("QUANTITY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QUANTITYSpecified {
            get {
                return this.qUANTITYFieldSpecified;
            }
            set {
                this.qUANTITYFieldSpecified = value;
                this.RaisePropertyChanged("QUANTITYSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int HEIGHT {
            get {
                return this.hEIGHTField;
            }
            set {
                this.hEIGHTField = value;
                this.RaisePropertyChanged("HEIGHT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HEIGHTSpecified {
            get {
                return this.hEIGHTFieldSpecified;
            }
            set {
                this.hEIGHTFieldSpecified = value;
                this.RaisePropertyChanged("HEIGHTSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<System.DateTime> DOPTDATE {
            get {
                return this.dOPTDATEField;
            }
            set {
                this.dOPTDATEField = value;
                this.RaisePropertyChanged("DOPTDATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DOPTDATESpecified {
            get {
                return this.dOPTDATEFieldSpecified;
            }
            set {
                this.dOPTDATEFieldSpecified = value;
                this.RaisePropertyChanged("DOPTDATESpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.primeton.com/interface2wcsService")]
    public partial class applyTaskResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int sTATUSField;
        
        private bool sTATUSFieldSpecified;
        
        private string mESSAGEField;
        
        private TaskInfo dATAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int STATUS {
            get {
                return this.sTATUSField;
            }
            set {
                this.sTATUSField = value;
                this.RaisePropertyChanged("STATUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool STATUSSpecified {
            get {
                return this.sTATUSFieldSpecified;
            }
            set {
                this.sTATUSFieldSpecified = value;
                this.RaisePropertyChanged("STATUSSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
                this.RaisePropertyChanged("MESSAGE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public TaskInfo DATA {
            get {
                return this.dATAField;
            }
            set {
                this.dATAField = value;
                this.RaisePropertyChanged("DATA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class applyTask1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.primeton.com/interface2wcsService", Order=0)]
        public WCS.WebService.applyTask applyTask;
        
        public applyTask1() {
        }
        
        public applyTask1(WCS.WebService.applyTask applyTask) {
            this.applyTask = applyTask;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class applyTaskResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.primeton.com/interface2wcsService", Order=0)]
        public WCS.WebService.applyTaskResponse applyTaskResponse;
        
        public applyTaskResponse1() {
        }
        
        public applyTaskResponse1(WCS.WebService.applyTaskResponse applyTaskResponse) {
            this.applyTaskResponse = applyTaskResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.primeton.com/interface2wcsService")]
    public partial class createTask : object, System.ComponentModel.INotifyPropertyChanged {
        
        private TaskInfo taskField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public TaskInfo task {
            get {
                return this.taskField;
            }
            set {
                this.taskField = value;
                this.RaisePropertyChanged("task");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.primeton.com/interface2wcsService")]
    public partial class createTaskResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int sTATUSField;
        
        private bool sTATUSFieldSpecified;
        
        private string mESSAGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int STATUS {
            get {
                return this.sTATUSField;
            }
            set {
                this.sTATUSField = value;
                this.RaisePropertyChanged("STATUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool STATUSSpecified {
            get {
                return this.sTATUSFieldSpecified;
            }
            set {
                this.sTATUSFieldSpecified = value;
                this.RaisePropertyChanged("STATUSSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
                this.RaisePropertyChanged("MESSAGE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createTask1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.primeton.com/interface2wcsService", Order=0)]
        public WCS.WebService.createTask createTask;
        
        public createTask1() {
        }
        
        public createTask1(WCS.WebService.createTask createTask) {
            this.createTask = createTask;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createTaskResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.primeton.com/interface2wcsService", Order=0)]
        public WCS.WebService.createTaskResponse createTaskResponse;
        
        public createTaskResponse1() {
        }
        
        public createTaskResponse1(WCS.WebService.createTaskResponse createTaskResponse) {
            this.createTaskResponse = createTaskResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.primeton.com/interface2wcsService")]
    public partial class updateScStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sEQIDField;
        
        private int nWKSTATUSField;
        
        private bool nWKSTATUSFieldSpecified;
        
        private string nWKMESSAGEField;
        
        private System.Nullable<System.DateTime> dOPTDATEField;
        
        private bool dOPTDATEFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string SEQID {
            get {
                return this.sEQIDField;
            }
            set {
                this.sEQIDField = value;
                this.RaisePropertyChanged("SEQID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int NWKSTATUS {
            get {
                return this.nWKSTATUSField;
            }
            set {
                this.nWKSTATUSField = value;
                this.RaisePropertyChanged("NWKSTATUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NWKSTATUSSpecified {
            get {
                return this.nWKSTATUSFieldSpecified;
            }
            set {
                this.nWKSTATUSFieldSpecified = value;
                this.RaisePropertyChanged("NWKSTATUSSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string NWKMESSAGE {
            get {
                return this.nWKMESSAGEField;
            }
            set {
                this.nWKMESSAGEField = value;
                this.RaisePropertyChanged("NWKMESSAGE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<System.DateTime> DOPTDATE {
            get {
                return this.dOPTDATEField;
            }
            set {
                this.dOPTDATEField = value;
                this.RaisePropertyChanged("DOPTDATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DOPTDATESpecified {
            get {
                return this.dOPTDATEFieldSpecified;
            }
            set {
                this.dOPTDATEFieldSpecified = value;
                this.RaisePropertyChanged("DOPTDATESpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.primeton.com/interface2wcsService")]
    public partial class updateScStatusResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int sTATUSField;
        
        private bool sTATUSFieldSpecified;
        
        private string mESSAGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int STATUS {
            get {
                return this.sTATUSField;
            }
            set {
                this.sTATUSField = value;
                this.RaisePropertyChanged("STATUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool STATUSSpecified {
            get {
                return this.sTATUSFieldSpecified;
            }
            set {
                this.sTATUSFieldSpecified = value;
                this.RaisePropertyChanged("STATUSSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
                this.RaisePropertyChanged("MESSAGE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateScStatus1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.primeton.com/interface2wcsService", Order=0)]
        public WCS.WebService.updateScStatus updateScStatus;
        
        public updateScStatus1() {
        }
        
        public updateScStatus1(WCS.WebService.updateScStatus updateScStatus) {
            this.updateScStatus = updateScStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateScStatusResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.primeton.com/interface2wcsService", Order=0)]
        public WCS.WebService.updateScStatusResponse updateScStatusResponse;
        
        public updateScStatusResponse1() {
        }
        
        public updateScStatusResponse1(WCS.WebService.updateScStatusResponse updateScStatusResponse) {
            this.updateScStatusResponse = updateScStatusResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.primeton.com/interface2wcsService")]
    public partial class updateStationStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sTATION_NUMBERField;
        
        private string sTATION_NAMEField;
        
        private string sTATION_TYPEField;
        
        private int sTATION_STATUSField;
        
        private bool sTATION_STATUSFieldSpecified;
        
        private string sTATION_MESSAGEField;
        
        private System.Nullable<System.DateTime> dOPTDATEField;
        
        private bool dOPTDATEFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string STATION_NUMBER {
            get {
                return this.sTATION_NUMBERField;
            }
            set {
                this.sTATION_NUMBERField = value;
                this.RaisePropertyChanged("STATION_NUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string STATION_NAME {
            get {
                return this.sTATION_NAMEField;
            }
            set {
                this.sTATION_NAMEField = value;
                this.RaisePropertyChanged("STATION_NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string STATION_TYPE {
            get {
                return this.sTATION_TYPEField;
            }
            set {
                this.sTATION_TYPEField = value;
                this.RaisePropertyChanged("STATION_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int STATION_STATUS {
            get {
                return this.sTATION_STATUSField;
            }
            set {
                this.sTATION_STATUSField = value;
                this.RaisePropertyChanged("STATION_STATUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool STATION_STATUSSpecified {
            get {
                return this.sTATION_STATUSFieldSpecified;
            }
            set {
                this.sTATION_STATUSFieldSpecified = value;
                this.RaisePropertyChanged("STATION_STATUSSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string STATION_MESSAGE {
            get {
                return this.sTATION_MESSAGEField;
            }
            set {
                this.sTATION_MESSAGEField = value;
                this.RaisePropertyChanged("STATION_MESSAGE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<System.DateTime> DOPTDATE {
            get {
                return this.dOPTDATEField;
            }
            set {
                this.dOPTDATEField = value;
                this.RaisePropertyChanged("DOPTDATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DOPTDATESpecified {
            get {
                return this.dOPTDATEFieldSpecified;
            }
            set {
                this.dOPTDATEFieldSpecified = value;
                this.RaisePropertyChanged("DOPTDATESpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.primeton.com/interface2wcsService")]
    public partial class updateStationStatusResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int sTATUSField;
        
        private bool sTATUSFieldSpecified;
        
        private string mESSAGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int STATUS {
            get {
                return this.sTATUSField;
            }
            set {
                this.sTATUSField = value;
                this.RaisePropertyChanged("STATUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool STATUSSpecified {
            get {
                return this.sTATUSFieldSpecified;
            }
            set {
                this.sTATUSFieldSpecified = value;
                this.RaisePropertyChanged("STATUSSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
                this.RaisePropertyChanged("MESSAGE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateStationStatus1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.primeton.com/interface2wcsService", Order=0)]
        public WCS.WebService.updateStationStatus updateStationStatus;
        
        public updateStationStatus1() {
        }
        
        public updateStationStatus1(WCS.WebService.updateStationStatus updateStationStatus) {
            this.updateStationStatus = updateStationStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateStationStatusResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.primeton.com/interface2wcsService", Order=0)]
        public WCS.WebService.updateStationStatusResponse updateStationStatusResponse;
        
        public updateStationStatusResponse1() {
        }
        
        public updateStationStatusResponse1(WCS.WebService.updateStationStatusResponse updateStationStatusResponse) {
            this.updateStationStatusResponse = updateStationStatusResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.primeton.com/interface2wcsService")]
    public partial class updateTaskStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sEQIDField;
        
        private int nWKSTATUSField;
        
        private bool nWKSTATUSFieldSpecified;
        
        private string nWKMESSAGEField;
        
        private System.Nullable<System.DateTime> dOPTDATEField;
        
        private bool dOPTDATEFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string SEQID {
            get {
                return this.sEQIDField;
            }
            set {
                this.sEQIDField = value;
                this.RaisePropertyChanged("SEQID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int NWKSTATUS {
            get {
                return this.nWKSTATUSField;
            }
            set {
                this.nWKSTATUSField = value;
                this.RaisePropertyChanged("NWKSTATUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NWKSTATUSSpecified {
            get {
                return this.nWKSTATUSFieldSpecified;
            }
            set {
                this.nWKSTATUSFieldSpecified = value;
                this.RaisePropertyChanged("NWKSTATUSSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string NWKMESSAGE {
            get {
                return this.nWKMESSAGEField;
            }
            set {
                this.nWKMESSAGEField = value;
                this.RaisePropertyChanged("NWKMESSAGE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<System.DateTime> DOPTDATE {
            get {
                return this.dOPTDATEField;
            }
            set {
                this.dOPTDATEField = value;
                this.RaisePropertyChanged("DOPTDATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DOPTDATESpecified {
            get {
                return this.dOPTDATEFieldSpecified;
            }
            set {
                this.dOPTDATEFieldSpecified = value;
                this.RaisePropertyChanged("DOPTDATESpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.primeton.com/interface2wcsService")]
    public partial class updateTaskStatusResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int sTATUSField;
        
        private bool sTATUSFieldSpecified;
        
        private string mESSAGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int STATUS {
            get {
                return this.sTATUSField;
            }
            set {
                this.sTATUSField = value;
                this.RaisePropertyChanged("STATUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool STATUSSpecified {
            get {
                return this.sTATUSFieldSpecified;
            }
            set {
                this.sTATUSFieldSpecified = value;
                this.RaisePropertyChanged("STATUSSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
                this.RaisePropertyChanged("MESSAGE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateTaskStatus1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.primeton.com/interface2wcsService", Order=0)]
        public WCS.WebService.updateTaskStatus updateTaskStatus;
        
        public updateTaskStatus1() {
        }
        
        public updateTaskStatus1(WCS.WebService.updateTaskStatus updateTaskStatus) {
            this.updateTaskStatus = updateTaskStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateTaskStatusResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.primeton.com/interface2wcsService", Order=0)]
        public WCS.WebService.updateTaskStatusResponse updateTaskStatusResponse;
        
        public updateTaskStatusResponse1() {
        }
        
        public updateTaskStatusResponse1(WCS.WebService.updateTaskStatusResponse updateTaskStatusResponse) {
            this.updateTaskStatusResponse = updateTaskStatusResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface interface2wcsServiceChannel : WCS.WebService.interface2wcsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class interface2wcsServiceClient : System.ServiceModel.ClientBase<WCS.WebService.interface2wcsService>, WCS.WebService.interface2wcsService {
        
        public interface2wcsServiceClient() {
        }
        
        public interface2wcsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public interface2wcsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public interface2wcsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public interface2wcsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCS.WebService.appleReworkLocatorResponse1 WCS.WebService.interface2wcsService.appleReworkLocator(WCS.WebService.appleReworkLocator1 request) {
            return base.Channel.appleReworkLocator(request);
        }
        
        public WCS.WebService.appleReworkLocatorResponse appleReworkLocator(WCS.WebService.appleReworkLocator appleReworkLocator1) {
            WCS.WebService.appleReworkLocator1 inValue = new WCS.WebService.appleReworkLocator1();
            inValue.appleReworkLocator = appleReworkLocator1;
            WCS.WebService.appleReworkLocatorResponse1 retVal = ((WCS.WebService.interface2wcsService)(this)).appleReworkLocator(inValue);
            return retVal.appleReworkLocatorResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WCS.WebService.appleReworkLocatorResponse1> WCS.WebService.interface2wcsService.appleReworkLocatorAsync(WCS.WebService.appleReworkLocator1 request) {
            return base.Channel.appleReworkLocatorAsync(request);
        }
        
        public System.Threading.Tasks.Task<WCS.WebService.appleReworkLocatorResponse1> appleReworkLocatorAsync(WCS.WebService.appleReworkLocator appleReworkLocator) {
            WCS.WebService.appleReworkLocator1 inValue = new WCS.WebService.appleReworkLocator1();
            inValue.appleReworkLocator = appleReworkLocator;
            return ((WCS.WebService.interface2wcsService)(this)).appleReworkLocatorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCS.WebService.applyTaskResponse1 WCS.WebService.interface2wcsService.applyTask(WCS.WebService.applyTask1 request) {
            return base.Channel.applyTask(request);
        }
        
        public WCS.WebService.applyTaskResponse applyTask(WCS.WebService.applyTask applyTask1) {
            WCS.WebService.applyTask1 inValue = new WCS.WebService.applyTask1();
            inValue.applyTask = applyTask1;
            WCS.WebService.applyTaskResponse1 retVal = ((WCS.WebService.interface2wcsService)(this)).applyTask(inValue);
            return retVal.applyTaskResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WCS.WebService.applyTaskResponse1> WCS.WebService.interface2wcsService.applyTaskAsync(WCS.WebService.applyTask1 request) {
            return base.Channel.applyTaskAsync(request);
        }
        
        public System.Threading.Tasks.Task<WCS.WebService.applyTaskResponse1> applyTaskAsync(WCS.WebService.applyTask applyTask) {
            WCS.WebService.applyTask1 inValue = new WCS.WebService.applyTask1();
            inValue.applyTask = applyTask;
            return ((WCS.WebService.interface2wcsService)(this)).applyTaskAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCS.WebService.createTaskResponse1 WCS.WebService.interface2wcsService.createTask(WCS.WebService.createTask1 request) {
            return base.Channel.createTask(request);
        }
        
        public WCS.WebService.createTaskResponse createTask(WCS.WebService.createTask createTask1) {
            WCS.WebService.createTask1 inValue = new WCS.WebService.createTask1();
            inValue.createTask = createTask1;
            WCS.WebService.createTaskResponse1 retVal = ((WCS.WebService.interface2wcsService)(this)).createTask(inValue);
            return retVal.createTaskResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WCS.WebService.createTaskResponse1> WCS.WebService.interface2wcsService.createTaskAsync(WCS.WebService.createTask1 request) {
            return base.Channel.createTaskAsync(request);
        }
        
        public System.Threading.Tasks.Task<WCS.WebService.createTaskResponse1> createTaskAsync(WCS.WebService.createTask createTask) {
            WCS.WebService.createTask1 inValue = new WCS.WebService.createTask1();
            inValue.createTask = createTask;
            return ((WCS.WebService.interface2wcsService)(this)).createTaskAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCS.WebService.updateScStatusResponse1 WCS.WebService.interface2wcsService.updateScStatus(WCS.WebService.updateScStatus1 request) {
            return base.Channel.updateScStatus(request);
        }
        
        public WCS.WebService.updateScStatusResponse updateScStatus(WCS.WebService.updateScStatus updateScStatus1) {
            WCS.WebService.updateScStatus1 inValue = new WCS.WebService.updateScStatus1();
            inValue.updateScStatus = updateScStatus1;
            WCS.WebService.updateScStatusResponse1 retVal = ((WCS.WebService.interface2wcsService)(this)).updateScStatus(inValue);
            return retVal.updateScStatusResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WCS.WebService.updateScStatusResponse1> WCS.WebService.interface2wcsService.updateScStatusAsync(WCS.WebService.updateScStatus1 request) {
            return base.Channel.updateScStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<WCS.WebService.updateScStatusResponse1> updateScStatusAsync(WCS.WebService.updateScStatus updateScStatus) {
            WCS.WebService.updateScStatus1 inValue = new WCS.WebService.updateScStatus1();
            inValue.updateScStatus = updateScStatus;
            return ((WCS.WebService.interface2wcsService)(this)).updateScStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCS.WebService.updateStationStatusResponse1 WCS.WebService.interface2wcsService.updateStationStatus(WCS.WebService.updateStationStatus1 request) {
            return base.Channel.updateStationStatus(request);
        }
        
        public WCS.WebService.updateStationStatusResponse updateStationStatus(WCS.WebService.updateStationStatus updateStationStatus1) {
            WCS.WebService.updateStationStatus1 inValue = new WCS.WebService.updateStationStatus1();
            inValue.updateStationStatus = updateStationStatus1;
            WCS.WebService.updateStationStatusResponse1 retVal = ((WCS.WebService.interface2wcsService)(this)).updateStationStatus(inValue);
            return retVal.updateStationStatusResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WCS.WebService.updateStationStatusResponse1> WCS.WebService.interface2wcsService.updateStationStatusAsync(WCS.WebService.updateStationStatus1 request) {
            return base.Channel.updateStationStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<WCS.WebService.updateStationStatusResponse1> updateStationStatusAsync(WCS.WebService.updateStationStatus updateStationStatus) {
            WCS.WebService.updateStationStatus1 inValue = new WCS.WebService.updateStationStatus1();
            inValue.updateStationStatus = updateStationStatus;
            return ((WCS.WebService.interface2wcsService)(this)).updateStationStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCS.WebService.updateTaskStatusResponse1 WCS.WebService.interface2wcsService.updateTaskStatus(WCS.WebService.updateTaskStatus1 request) {
            return base.Channel.updateTaskStatus(request);
        }
        
        public WCS.WebService.updateTaskStatusResponse updateTaskStatus(WCS.WebService.updateTaskStatus updateTaskStatus1) {
            WCS.WebService.updateTaskStatus1 inValue = new WCS.WebService.updateTaskStatus1();
            inValue.updateTaskStatus = updateTaskStatus1;
            WCS.WebService.updateTaskStatusResponse1 retVal = ((WCS.WebService.interface2wcsService)(this)).updateTaskStatus(inValue);
            return retVal.updateTaskStatusResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WCS.WebService.updateTaskStatusResponse1> WCS.WebService.interface2wcsService.updateTaskStatusAsync(WCS.WebService.updateTaskStatus1 request) {
            return base.Channel.updateTaskStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<WCS.WebService.updateTaskStatusResponse1> updateTaskStatusAsync(WCS.WebService.updateTaskStatus updateTaskStatus) {
            WCS.WebService.updateTaskStatus1 inValue = new WCS.WebService.updateTaskStatus1();
            inValue.updateTaskStatus = updateTaskStatus;
            return ((WCS.WebService.interface2wcsService)(this)).updateTaskStatusAsync(inValue);
        }
    }
}
