//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RFIDControl.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\Project\\Source2\\黄冈二期立库WCS\\RFIDApp2001\\bin\\Debug\\RFIDApp2001.exe")]
        public string ExecPath2001 {
            get {
                return ((string)(this["ExecPath2001"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\Project\\Source2\\黄冈二期立库WCS\\RFIDApp2002\\bin\\Debug\\RFIDApp2002.exe")]
        public string ExecPath2002 {
            get {
                return ((string)(this["ExecPath2002"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\Project\\Source2\\黄冈二期立库WCS\\RFIDApp2007\\bin\\Debug\\RFIDApp2007.exe")]
        public string ExecPath2007 {
            get {
                return ((string)(this["ExecPath2007"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\Project\\Source2\\黄冈二期立库WCS\\RFIDApp2019\\bin\\Debug\\RFIDApp2019.exe")]
        public string ExecPath2019 {
            get {
                return ((string)(this["ExecPath2019"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\Project\\Source2\\黄冈二期立库WCS\\RFIDApp20012\\bin\\Debug\\RFIDApp20012.exe")]
        public string ExecPath20012 {
            get {
                return ((string)(this["ExecPath20012"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\Project\\Source2\\黄冈二期立库WCS\\RFIDApp20022\\bin\\Debug\\RFIDApp20022.exe")]
        public string ExecPath20022 {
            get {
                return ((string)(this["ExecPath20022"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\Project\\Source2\\RFIDApp2016\\bin\\Debug\\RFIDApp2015.exe")]
        public string ExecPath2015 {
            get {
                return ((string)(this["ExecPath2015"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\Project\\Source2\\黄冈二期立库WCS\\RFIDApp2017\\bin\\Debug\\RFIDApp2017.exe")]
        public string ExecPath2017 {
            get {
                return ((string)(this["ExecPath2017"]));
            }
        }
    }
}
